name: Deployment
'on':
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          command_timeout: 5m
          script_stop: true
          script: |
                  cd Dotsimus
                  pm2 stop lib/index.js
                  pm2 flush
                  echo app stopped
                  git pull
                  npm install
                  pm2 start lib/index.js --log logs.log --time
                  echo deployment completed
